### ISSUE TITLE
IRTF CFRG BLS discussion

### ISSUE THREAD

**Issue by burdges** [filecoin-project/bls-signatures#19]
I forget where we previously discussed matters and issues are not enabled on https://github.com/filecoin-project/pairing so I'll raise the issue here.

It's maybe worth basing the hashing-to-the-curve code off the code that gets discussed on the IRTF forum, which I believe to be
https://github.com/algorand/bls_sigs_ref/blob/master/rust-impl/
https://github.com/algorand/pairing-plus/tree/master/src

There are some questionable decisions being made there for IRTF process, like using HKDF-SHA2 possibly without the layers of hashing in the best places, but at least the arithmetic gets better discussed.  Also, their ff version is outdated and their trait layout is obsoleted by the group crate, but the hashing functionality appears slightly more orthogonal, so maybe we could glue it onto a the more recent zkcrypto paring crate?

**Comment by burdges** [comment]
Actually, their HKDF usage makes quite a mess of the code, so ugh..

**Comment by burdges** [comment]
We should discuss the IRTF BLS draft so maybe reopen for now.

Also, I think everyone here wants https://github.com/mmaker/draft-irtf-cfrg-hash-to-curve/commit/3c10ce7f37fb281b4bdc423374fe6df5c4dfe9f9 by @mmaker but not obviously implemented anywhere yet.

**Comment by burdges** [comment]
Appears the old issue is https://github.com/filecoin-project/research/issues/53

**Comment by dignifiedquire** [comment]
This is done in `master`. I pulled the hash-to-curve operations into filecoin-project/pairing
