### ISSUE TITLE
Minimal-signature-size or Minimal-pubkey-size Variant?

### ISSUE THREAD

**Issue by jonarmani** [filecoin-project/bls-signatures#44]
Which variant does this crate use by default? Is there a way to change it?

Variant reference: https://datatracker.ietf.org/doc/html/draft-irtf-cfrg-bls-signature-00#section-2.1

**Comment by dignifiedquire** [comment]
It uses `Minimal-pubkey-size` with public keys are points in G1, signatures are points in G2.
